#!/bin/sh

rm -f config.*
rm -f src/Makevars
rm -rf autom4te.cache
rm -f libssh2.zip
rm -rf libssh2
rm -rf src/libssh2
rm -f openssl.zip
rm -rf openssl
rm -rf src/openssl
rm -f local320.zip
rm -rf src/zlib
rm -f src/*.def
rm -f src/*.o
rm -f src/*.so
rm -rf src-x64
rm -rf src-i386
rm -f src/libgit2/*.o
rm -f src/libgit2/hash/*.o
rm -f src/libgit2/transports/*.o
rm -f src/libgit2/unix/*.o
rm -f src/libgit2/win32/*.o
rm -f src/libgit2/xdiff/*.o
rm -f src/http-parser/*.o
rm -f src/regex/*.o
