#!/bin/sh

rm -f config.*
rm -f src/Makevars
rm -rf autom4te.cache
rm -f src/*.o
rm -f src/*.so
rm -f src/libmygit.a
rm -f src/libgit2/src/*.o
rm -f src/libgit2/src/hash/*.o
rm -f src/libgit2/src/transports/*.o
rm -f src/libgit2/src/unix/*.o
rm -f src/libgit2/src/xdiff/*.o
rm -f src/libgit2/deps/http-parser/*.o
rm -f src/libgit2/deps/regex/*.o
rm -rf src/libgit2/deps/libssh2
